---
- name: install k3s on main node
  shell: |
    set -o pipefail
    echo $K3S_KUBECONFIG_MODE && echo $INSTALL_K3S_EXEC && curl -sfL https://get.k3s.io | sh -
  environment:
    K3S_KUBECONFIG_MODE: "{{ k3s_kubeconfig_mode }}"
    INSTALL_K3S_EXEC: "{{ install_k3s_exec }}"
  args:
    executable: /bin/bash
  register: k3s_main_install_result
  changed_when: "k3s_main_install_result.rc == 0"
  become: yes
  run_once: yes

- name: results of installation
  debug: var=k3s_main_install_result.stdout_lines
  when: k3s_main_install_result is changed

- name: fetch k3s.yaml
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/k3s.yaml
    flat: yes
  become: yes
  run_once: yes

- name: update master ip in k3s.yaml
  replace:
    path: /tmp/k3s.yaml
    regexp: '127\.0\.0\.1'
    replace: "{{ hostvars[groups['k3s_masters'][0]]['ansible_ens4']['ipv4']['address'] }}"
  run_once: yes
  delegate_to: localhost