---
- name: apt autoremove
  apt:
    autoremove: yes
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: update all apt packages
  apt:
    upgrade: dist
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: install apt packages
  apt:
    name: "{{ apt_packages }}"
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: install snaps
  snap:
    name: "{{ snap_packages }}"
  become: yes